services:
  # Service PHP (Le moteur)
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: slim_php
    volumes:
      - .:/var/www/html
    depends_on:
      - mariadb
    networks:
      - app_network

  # Service Nginx (Le serveur web)
  web:
    image: nginx:alpine
    container_name: slim_nginx
    ports:
      - "${APP_PORT:-8000}:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - app_network

  # Service MariaDB (La base de donn√©es)
  mariadb:
    image: mariadb:latest
    container_name: slim_mariadb
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-rootpassword}
      MYSQL_DATABASE: ${DB_NAME:-slim_db}
      MYSQL_USER: ${DB_USER:-slim_user}
      MYSQL_PASSWORD: ${DB_PASSWORD:-slim_password}
    ports:
      - "${DB_PORT:-3306}:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  mariadb_data:
    driver: local